name: Test Extract Instagram VersionCodes

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test APKCombo
        run: |
          curl -L -I \
            -A "Mozilla/5.0" \
            "https://apkcombo.com/instagram/com.instagram.android/download/apk"
